apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox-deployment
  template:
    metadata:
      labels:
        app: busybox-deployment
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "sleep 3600"]
        env:
        - name: name
          value: "Nagham"
        - name: age
          valueFrom:
            configMapKeyRef:
              name: k8s-configmap
              key: my-nice-age
        resources: {}   

