apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-deployment
  name: k8s-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-deployment
  type: NodePort
status:
  loadBalancer: {}
